// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxZURw-5tZqpt_cfoP_S7zme6cDwsZVJs',
    appId: '1:863761100815:web:b8995facaeb1422bd0f37a',
    messagingSenderId: '863761100815',
    projectId: 'my-wedding-calls-123',
    authDomain: 'my-wedding-calls-123.firebaseapp.com',
    storageBucket: 'my-wedding-calls-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFRhpjGFJJlaZa88Ju-oswYyJCVvXa-cA',
    appId: '1:863761100815:android:90125b50fd21f00ed0f37a',
    messagingSenderId: '863761100815',
    projectId: 'my-wedding-calls-123',
    storageBucket: 'my-wedding-calls-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-qVedgkO45x7AKH-ojsBcGWX78bk_LhI',
    appId: '1:863761100815:ios:c593f312f284a258d0f37a',
    messagingSenderId: '863761100815',
    projectId: 'my-wedding-calls-123',
    storageBucket: 'my-wedding-calls-123.firebasestorage.app',
    iosBundleId: 'com.example.weddingCallsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-qVedgkO45x7AKH-ojsBcGWX78bk_LhI',
    appId: '1:863761100815:ios:c593f312f284a258d0f37a',
    messagingSenderId: '863761100815',
    projectId: 'my-wedding-calls-123',
    storageBucket: 'my-wedding-calls-123.firebasestorage.app',
    iosBundleId: 'com.example.weddingCallsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxZURw-5tZqpt_cfoP_S7zme6cDwsZVJs',
    appId: '1:863761100815:web:19aeb4f600107a9ed0f37a',
    messagingSenderId: '863761100815',
    projectId: 'my-wedding-calls-123',
    authDomain: 'my-wedding-calls-123.firebaseapp.com',
    storageBucket: 'my-wedding-calls-123.firebasestorage.app',
  );

}